services:
  sherlock-ai-assignment-service:
    container_name: sherlock-ai-assignment-service
    image: ghcr.io/lockhart07/sherlock-ai-assignment:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; r=requests.get('http://localhost:9000/ping'); r.raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      SECRET_KEY: your-super-secret-key-change-this-in-production 
      GOOGLE_CLIENT_ID: 1004465075402-250h5aofijcdk49naeqs869ledj50uoh.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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


